name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: cargo install just && rustup target add aarch64-linux-android && cargo install cargo-ndk
    - name: Build
      run: just flash-release
    - name: Run tests
      run: cargo test --verbose
