name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Just
      run: cargo install just
    - name: Set target
      run: rustup target add aarch64-linux-android
    - name: Cargo NDK
      run: cargo install cargo-ndk
    - name: Build
      run: just package-release
    - name: KernelSu
      run: just flash-release
